### ISSUE TITLE
UBSAN warning in dfltcc_inflate_disable 

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#1204]
```
2022-03-18T18:13:26.5447156Z 2: inflate init: 8976 allocated
2022-03-18T18:13:26.5451191Z 2: /home/actions-runner/_work/zlib-ng/zlib-ng/arch/s390/dfltcc_inflate.c:138:5: runtime error: null pointer passed as argument 1, which is declared to never be null
2022-03-18T18:13:26.5455643Z 2:     #0 0x102ffed in dfltcc_inflate_disable (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x102ffed)
2022-03-18T18:13:26.5459479Z 2:     #1 0x1014c25 in inflatePrime (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1014c25)
2022-03-18T18:13:26.5463011Z 2:     #2 0x1000d6d in main (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1000d6d)
2022-03-18T18:13:26.5466716Z 2:     #3 0x1072eb1 in __libc_start_main (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1072eb1)
2022-03-18T18:13:26.5470194Z 2:     #4 0x1001943  (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1001943)
```

https://github.com/zlib-ng/zlib-ng/runs/5604807137?check_suite_focus=true @iii-i

**Comment by iii-i** [comment]
Sorry, I didn't notice this issue and answered here: https://github.com/zlib-ng/zlib-ng/pull/1195#issuecomment-1073828379

**Comment by nmoinvaz** [comment]
Looks like it is gone now that the other commit has been merged.
