### ISSUE TITLE
ubsan fails with unsigned integer overflow

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#187]
While running "make check" with ubsan (the undefined behavior sanitizer), the fuzzers are failing with:
```
/src/zlib-ng/adler32.c:91:19: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'size_t' (aka 'unsigned long')
/src/zlib-ng/adler32.c:136:19: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'size_t' (aka 'unsigned long')
/src/zlib-ng/arch/x86/deflate_quick.c:233:22: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
/src/zlib-ng/arch/x86/fill_window_sse.c:52:28: runtime error: unsigned integer overflow: 1 - 8192 cannot be represented in type 'unsigned int'
/src/zlib-ng/inflate.c:972:32: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
```

**Comment by mtl1979** [comment]
Most of these seem false positives... in while loops 0 equals false and such stops the loop.
The one in fill_window_sse.c should return 0 instead of negative number, as in saturated substraction.

**Comment by sebpop** [comment]
easy fix for the while loops.  The other two need more attention.

**Comment by mtl1979** [comment]
I assume the one in deflate_quick.c is caused by ```dist``` being 0... as such dist - 1 = -1, which can be avoided by testing if ```dist = 0``` or ```(dist - 1) < (s->w_size - 1)```...

fill_window_sse.c error is most likely caused by s->match_start being 1 ... so it needs to be rewritten as
```s->match_start = (s->match_start >= wsize) ? s->match_start - wsize : 0;```

**Comment by sebpop** [comment]
> testing if `dist = 0` or `(dist - 1) < (s->w_size - 1)`...

That fails with:
```
/src/zlib-ng/arch/x86/deflate_quick.c:152:33: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
/src/zlib-ng/arch/x86/deflate_quick.c:152:12: runtime error: index 4294967295 out of bounds for type 'const unsigned int [8192]'
```
and then it passes with the following change:
```
--- a/arch/x86/deflate_quick.c
+++ b/arch/x86/deflate_quick.c
@@ -230,7 +230,7 @@ ZLIB_INTERNAL block_state deflate_quick(deflate_state *s, int flush) {
             hash_head = quick_insert_string(s, s->strstart);
             dist = s->strstart - hash_head;
-            if (dist == 0 || (dist-1) < (s->w_size - 1)) {
+            if (dist > 0 && (dist-1) < (s->w_size - 1)) {
                 match_len = compare258(s->window + s->strstart, s->window + s->strstart - dist);
                 if (match_len >= MIN_MATCH) {
```

**Comment by sebpop** [comment]
> `s->match_start = (s->match_start >= wsize) ? s->match_start - wsize : 0;`

After this change it started failing with 
```
MemorySanitizer: use-of-uninitialized-value
    #0 0x4e8193 in fill_window_sse /src/zlib-ng/arch/x86/fill_window_sse.c:52:30
```

**Comment by mtl1979** [comment]
That stack trace is too short to deduct how to fix the issue... obviously match_start needs to be initialized when the struct is originally allocated.

**Comment by sebpop** [comment]
Here is a longer trace:
```
    #0 0x4e8193 in fill_window_sse /src/zlib-ng/arch/x86/fill_window_sse.c:52:30
    #1 0x4e9254 in deflate_quick /src/zlib-ng/arch/x86/deflate_quick.c:220:13
    #2 0x4ad375 in zng_deflate /src/zlib-ng/deflate.c:951:18
    #3 0x49fef1 in test_large_deflate /src/zlib-ng/test/example.c:264:11
    #4 0x4a3232 in main /src/zlib-ng/test/example.c:536:5
```
