### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow in read_buf() deflate.c:1122

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#194]
```
==21==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000d1 at pc 0x0000004eaceb bp 0x7ffc0b9f3f80 sp 0x7ffc0b9f3730
READ of size 3 at 0x6020000000d1 thread T0
SCARINESS: 15 (3-byte-read-heap-buffer-overflow)
    #0 0x4eacea in __asan_memmove /src/llvm/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:31
    #1 0x5ccf7d in read_buf /src/zlib-ng/deflate.c:1122:9
    #2 0x5e9a8b in fill_window_sse /src/zlib-ng/arch/x86/fill_window_sse.c:106:13
    #3 0x5cf0f9 in deflate_medium /src/zlib-ng/deflate_medium.c:215:13
    #4 0x5c6f4d in zng_deflate /src/zlib-ng/deflate.c:951:18
    #5 0x5bf769 in test_flush /src/zlib-ng/test/fuzz/compress_fuzzer.c:250:9
    #6 0x5c09e1 in LLVMFuzzerTestOneInput /src/zlib-ng/test/fuzz/compress_fuzzer.c:414:3
    #7 0x55a0b2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:575:15
    #8 0x557ed7 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:481:3
    #9 0x55d46a in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:770:5
    #10 0x55e798 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:810:3
    #11 0x53cd76 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:766:6
    #12 0x52ffcc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #13 0x7f58e230682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x41cd18 in _start (/out/compress_fuzzer+0x41cd18)

0x6020000000d1 is located 0 bytes to the right of 1-byte region [0x6020000000d0,0x6020000000d1)
allocated by thread T0 here:
    #0 0x52bc38 in operator new[](unsigned long) /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:109
    #1 0x559e64 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:562:23
    #2 0x557ed7 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:481:3
    #3 0x55d46a in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:770:5
    #4 0x55e798 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:810:3
    #5 0x53cd76 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:766:6
    #6 0x52ffcc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f58e230682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/llvm/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:31 in __asan_memmove
Shadow bytes around the buggy address:
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff8000: fa fa 00 00 fa fa 00 fa fa fa 00 fa fa fa 00 fa
=>0x0c047fff8010: fa fa fd fa fa fa 01 fa fa fa[01]fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==21==ABORTING
```

**Comment by mtl1979** [comment]
Passing too small buffer to zlib-ng is not a bug, it's user fault.

**Comment by sebpop** [comment]
This error comes from test_flush() in example.c where it sets `c_stream.avail_in = 3;`.

Shouldn't zlib-ng check and warn for too small buffers as a runtime assert check?

**Comment by mtl1979** [comment]
@sebpop The problem is that the data structure is writable by "outside world", so zlib-ng can't trust it to determine how big the allocation actually is.

**Comment by sebpop** [comment]
Understood. Thanks for the explanation. The patch addresses the problem by ensuring that there are enough bytes for test_flush to not trigger the problem.

**Comment by mtl1979** [comment]
@Dead2 will merge all the patches that have no issues when he is online...

**Comment by sebpop** [comment]
@mtl1979 could you please have a look at the last failed TravisCI build on the aarch64 side?
Do you have an idea why we get the contents of the files instead of their names on the command line?
There is something that I don't catch: maybe they are using a different shell?

**Comment by sebpop** [comment]
I think https://github.com/Dead2/zlib-ng/pull/181/commits/69b171f0b15dd4bdfb79385b10be7a0c21f8eb29 should fix it.

**Comment by mtl1979** [comment]
@sebpop It's not using ${QEMU_RUN} for cross-compiled executable...

**Comment by sebpop** [comment]
Thanks @mtl1979.
I was under the impression that TravisCI was running the processes natively on aarch64.

**Comment by mtl1979** [comment]
All the TravisCI instances are virtual machines... None of them are actually real hardware.

**Comment by sebpop** [comment]
That fixed it.  Thanks again @mtl1979!
I see that all testing is virtualized on top of x86_64.  Nice.

**Comment by mtl1979** [comment]
Yeah... They're running Ubuntu Trusty (14.04), so testing new code is pain-in-the-ass, because their gcc and libc versions are literally prehistoric, pretty much first test versions that even support ARM and PPC.

**Comment by sebpop** [comment]
I disabled `test_large_deflate()` and `test_large_inflate()` in `compress_fuzzer` for now as they are still producing errors at least two errors:
```
Running: libz.a
deflate not greedy
```
```
Running: deflate_quick.lo
deflate large should report Z_STREAM_END
```

**Comment by mtl1979** [comment]
"deflate not greedy" is most likely caused by having too small buffer. the second error is just consequence of the first error...

**Comment by sebpop** [comment]
Thanks for the hint!  I got the first one working by adding
```
  PREFIX(deflateParams)(&c_stream, Z_BEST_COMPRESSION, Z_FILTERED);
```

**Comment by mtl1979** [comment]
Obviously increasing compression level means output buffer can be smaller.

**Comment by sebpop** [comment]
To fix the orther error, I had to increase the buffer size: https://github.com/Dead2/zlib-ng/pull/181/commits/2b7f385f0608f80a9dd04b62332c751aa052f373

**Comment by sebpop** [comment]
I have the impression that these two functions test_large_deflate() and test_large_inflate() are quite brittle, and we may end up with similar errors in the future. The fuzzers may get stuck on such errors.

**Comment by mtl1979** [comment]
It took me years to understand how most of the internals work, but there is still a lot of stuff that is too rocket science for me.

**Comment by sebpop** [comment]
The CI turned green just now.
Thanks @mtl1979 for your help!

**Comment by mtl1979** [comment]
I try to help when I can and have enough time...
