### ISSUE TITLE
MemorySanitizer: SEGV in deflate_quick.c:134

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#197]
```
MemorySanitizer:DEADLYSIGNAL
--
  | ==1==ERROR: MemorySanitizer: SEGV on unknown address 0x730000020000 (pc 0x0000005b6ce4 bp 0x7fff59adb5e0 sp 0x7fff59adb570 T1)
  | ==1==The signal is caused by a WRITE memory access.
  | #0 0x5b6ce3 in quick_send_bits zlib-ng/arch/x86/deflate_quick.c:134:48
  | #1 0x5b5752 in deflate_quick zlib-ng/arch/x86/deflate_quick.c:243:21
  | #2 0x590a15 in zng_deflate zlib-ng/deflate.c:952:18
  | #3 0x587165 in zng_compress2 zlib-ng/compress.c:59:15
  | #4 0x5866d3 in check_compress_level zlib-ng/test/fuzz/compress_fuzzer.c:22:3
  | #5 0x5862d8 in LLVMFuzzerTestOneInput zlib-ng/test/fuzz/compress_fuzzer.c:74:3
  | #6 0x4e9b48 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:575:15
  | #7 0x4a2f66 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
  | #8 0x4b3adb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
  | #9 0x4a2091 in main /src/libfuzzer/FuzzerMain.cpp:20:10
  | #10 0x7fb8919b082f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/libc-start.c:291
  | #11 0x41ec68 in _start
  | MemorySanitizer can not provide additional info.
  | SUMMARY: MemorySanitizer: SEGV (/mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_zlib-ng_7ead0a3e4980f024583384fd355b6e3ddd4b2ca2/revisions/compress_fuzzer+0x5b6ce3)
```

**Comment by sebpop** [comment]
We are writing 4 bytes:
```
*(unsigned *)(s->pending_buf + s->pending) = out;
```
at this address:
```
(gdb) p /x s->pending_buf + s->pending
$16 = 0x73000001fffd
(gdb) p /x s->pending_buf + s->pending + 4
$17 = 0x730000020001
(gdb) p /x s->pending_buf_size
$18 = 0x10000
```
and so that write runs over the allocated buffer by 1 byte.

**Comment by sebpop** [comment]
An alternative fix for this bug is to call flush_pending earlier, like so:
```
--- a/arch/x86/deflate_quick.c
+++ b/arch/x86/deflate_quick.c
@@ -211,7 +211,7 @@ ZLIB_INTERNAL block_state deflate_quick(deflate_state *s, int flush) {
     }
 
     do {
-        if (s->pending + 4 >= s->pending_buf_size) {
+        if (s->pending + 6 >= s->pending_buf_size) {
             flush_pending(s->strm);
             return need_more;
         }
```

**Comment by sebpop** [comment]
I think I like the second fix better: it avoids writes to a different page which are expensive.

**Comment by sebpop** [comment]
I like the third fix better: it addresses the out of buffer writes problem and in the same time it reduces the number of writes to memory.

**Comment by sebpop** [comment]
The last patch integrates a fix for undefined behavior due to shifts that would send bits over the 32 allowed bits. The separate patch looks like this:
https://github.com/Dead2/zlib-ng/pull/181/commits/a26b1bbde1a372e529b7f2fbeb8e205464bb91ad
