### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value in makefixed.c:43

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#437]
```
  Uninitialized value was stored to memory at
    #0 0x427893 in __msan_memcpy.part.330 (/home/runner/work/zlib-ng/zlib-ng/makefixed+0x427893)
    #1 0x49cc0a in write_bytes (/home/runner/work/zlib-ng/zlib-ng/makefixed+0x49cc0a)

  Uninitialized value was created by an allocation of 'state' in the stack frame of function 'makefixed'
    #0 0x495e90 in makefixed /home/runner/work/zlib-ng/zlib-ng/tools/makefixed.c:43

==5120==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x49d58a in llvm_gcda_end_file (/home/runner/work/zlib-ng/zlib-ng/makefixed+0x49d58a)
    #1 0x49cad3 in llvm_writeout_files (/home/runner/work/zlib-ng/zlib-ng/makefixed+0x49cad3)
    #2 0x427523 in MSanAtExitWrapper(void*) (/home/runner/work/zlib-ng/zlib-ng/makefixed+0x427523)
    #3 0x7f968411b040  (/lib/x86_64-linux-gnu/libc.so.6+0x43040)
    #4 0x7f968411b139 in exit (/lib/x86_64-linux-gnu/libc.so.6+0x43139)
    #5 0x7f96840f9b9d in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b9d)
    #6 0x41aa89 in _start (/home/runner/work/zlib-ng/zlib-ng/makefixed+0x41aa89)
```

**Comment by nmoinvaz** [comment]
The bug looks like it may be in zlib as well.

**Comment by nmoinvaz** [comment]
The thing to do here might be to memset state parameter before the call to buildfixedtables but I'm not 100% sure.
